#+TITLE: My emacs config
#+AUTHOR: Annwan

* Basic tweaks that maybe should have been defaults

** The tutorial

I only need to see the tutorial once.
#+begin_src elisp
(setq inhibit-startup-message t)
#+end_src

** GUI widgets

Yeah, those only take room and the screen without beeing of any use, lets remove them.

#+begin_src elisp
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
#+end_src
   
** Display some more stuff

Highlight current line

#+begin_src elisp
(global-hl-line-mode t)
#+end_src

Display line and column number in modeline
   
#+begin_src elisp
(line-number-mode t)
(column-number-mode t)
#+end_src

** Tabs are evil

See [[https://www.emacswiki.org/emacs/TabsAreEvil][Emacs Wiki]]

#+begin_src elisp
(setq-default indent-tabs-mode nil)
#+end_src

* Configuring builtin stuff

** Org mode

Indentation messes code blocks

#+begin_src elisp
(setq org-adapt-indentation nil)
(setq org-edit-src-content-indentation 0)
#+end_src

** ElDoc

Documentation for elisp

#+begin_src elisp
(add-hook 'emacs-lisp-mode-hook 'eldoc-mode)
#+end_src

** Fonts

Using the nerd font patched Source Code Pro.
   
#+begin_src elisp
(add-to-list 'default-frame-alist '(font . "SauceCodePro Nerd Font-12"))
#+end_src
   
** =prettify-symbols=

We want to enable it everywhere
   
#+begin_src elisp
(global-prettify-symbols-mode +1)
#+end_src

Now configuration mode per mode

*** Org

For org mode we want the following:
   
- replace the series of =*= with bullets
- replace =#+begin_src=, =#+begin_quote=, =#+begin_example= and their corresponding end tags with more estheticaly pleasing symbols
- replace some of the other =#+...= tags with descriptive characters
      
#+begin_src elisp
(add-hook 'org-mode-hook
 (lambda ()
  (push '("#+TITLE:" . ?“) prettify-symbols-alist)
  (push '("#+title:" . ?“) prettify-symbols-alist)
  (push '("#+AUTHOR:" . ?…) prettify-symbols-alist)
  (push '("#+author:" . ?…) prettify-symbols-alist)
  (push '("#+begin_src" . ?↓) prettify-symbols-alist)
  (push '("#+end_src" . ?↑) prettify-symbols-alist)
  (push '("#+begin_example" . ?‹) prettify-symbols-alist)
  (push '("#+end_example" . ?›) prettify-symbols-alist)
  (push '("#+begin_quote" . ?«) prettify-symbols-alist)
  (push '("#+end_quote" . ?») prettify-symbols-alist)
  (push '("*" . ?●) prettify-symbols-alist)
  (push '("**" . ?◉) prettify-symbols-alist)
  (push '("***" . ?○) prettify-symbols-alist)))
#+end_src

*** Haskell

We will replace sevral of the multi-characters operators and keywords

#+begin_src elisp
(add-hook 'haskell-mode-hook
 (lambda ()
  (push '("/=" . ?≠) prettify-symbols-alist)
  (push '("::" . ?⸬) prettify-symbols-alist)
  (push '("\\" . ?λ) prettify-symbols-alist)
  (push '("=>" . ?⇒) prettify-symbols-alist)
  (push '("->" . ?→) prettify-symbols-alist)))
#+end_src
    
* Setup use for packages

** Require and initialize the package module

Without it we can't do anything

#+begin_src elisp
(require 'package)
(package-initialize)
#+end_src

** Add MELPA to the archive list

GNU ELPA is nice but clearly does not have everything we need

#+begin_src elisp
(add-to-list 'package-archives
 '("melpa" . "https://melpa.org/packages/") t)
#+end_src

** =use-package=

This is a package that will allow us to more easily manage other packages
   
#+begin_src elisp
(unless (package-installed-p 'use-package)
 (package-refresh-contents)
 (package-install 'use-package))
#+end_src

* External Packages and their configuration
** Theme

I use =doom-monokai-spectrum= from the =doom-themes= package

#+begin_src elisp
(use-package doom-themes
 :ensure t
 :config
 (load-theme 'doom-monokai-spectrum))
 #+end_src
** Autocompletion in mini-buffers
   For this task I use =ivy= and =counsel=

#+begin_src elisp
(use-package counsel
 :ensure t
 :config
 (counsel-mode))
#+end_src
   
** Autocompletion in files

=company= is the best auto completion package currently available.
    
#+begin_src elisp
(use-package company
 :ensure t
 :config
 (global-company-mode))
#+end_src

** Git support

=magit= rules.

#+begin_src elisp
(use-package magit
 :ensure t
 :bind ("C-x g" . magit-status))
#+end_src

** Haskell

#+begin_src elisp
(use-package haskell-mode
 :bind
 (:map haskell-mode-map
  ("<f8>" . haskell-navigate-imports))
 :ensure t)
#+end_src

** Projects

=projectile= adds the notion of projects to emacs, which is really handy

#+begin_src elisp
(use-package projectile
  :bind
  (:map projectile-mode-map
        ("C-c p" . projectile-command-map))
  :init
  (projectile-mode +1)
  :ensure t)
#+end_src

** Keybinds popup

Emacs has loads of keybinds, you end up remembering those you use often but
=which-key= helps a lot when you have a doubt

#+begin_src elisp
(use-package which-key
  :init
  (which-key-mode +1)
  (add-to-list 'which-key-replacement-alist '(("TAB" . nil) . ("⇥" . nil)))
  (add-to-list 'which-key-replacement-alist '(("DEL" . nil) . ("⌫" . nil)))
  (add-to-list 'which-key-replacement-alist '(("RET" . nil) . ("↵" . nil)))
  (add-to-list 'which-key-replacement-alist '(("SPC" . nil) . ("␣" . nil)))  
  :ensure t)
#+end_src

** Markdown support

READMEs and more

#+begin_src elisp
(use-package markdown-mode
  :ensure t
  :commands (markdown-mode gfm-mode)
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'" . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :init (setq markdown-command "multimarkdown"))
#+end_src

** Edit indirect

Edit code blocks of outline documents in a dedicated buffer

#+begin_src elisp
(use-package edit-indirect
  :ensure t)
#+end_src

** Smart parenthesis

Auto closing parens, brackets, braces and more

#+begin_src elisp
(use-package smartparens
  :init
  (smartparens-global-mode 1)
  :ensure t)
#+end_src

** TeX

*** PDF Preview

#+begin_src elisp
(use-package pdf-tools
  :ensure t
  :config
  (pdf-tools-install)
  (setq-default pdf-view-display-size 'fit-page)
  (setq pdf-annot-activate-created-annotations t))
#+end_src

*** References and citatitons

#+begin_src elisp
(use-package reftex
  :ensure t
  :defer t
  :config (setq reftex-cite-prompt-optional-args t))
#+end_src

*** Autocompletion

#+begin_src elisp
(use-package company-auctex
  :ensure t
  :init (company-auctex-init))
#+end_src

*** Building stuff

#+begin_src elisp
(use-package auctex-latexmk
  :ensure t
  :config
  (auctex-latexmk-setup)
  (setq auctex-latexmk-inherit-TeX-PDF-mode t))
#+end_src

*** Everything else

#+begin_src elisp
(use-package tex
  :ensure auctex
  :mode ("\\.tex\\'" . latex-mode)
  :config (progn
            (setq TeX-source-correlate-mode t)
            (setq TeX-source-correlate-method 'synctex)
            (setq TeX-auto-save t)
            (setq TeX-parse-self t)
            (setq reftex-plug-into-AUCTeX t)
            (setq-default TeX-master "main.tex")
            (pdf-tools-install)
            (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
                  TeX-source-correlate-start-server t)
            (add-hook 'TeX-after-compilation-finished-functions
                      #'TeX-revert-document-buffer)
            (add-hook 'LaTeX-mode-hook
                      (lambda ()
                        (reftex-mode t)))))
#+end_src

** Lua

Lua developement. I do a whole bunch of that

#+begin_src elisp
(use-package lua-mode
  :ensure t
  :config
  (setq lua-indent-level 4))
#+end_src
